(()=>{'use strict';
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let csrf='',orders=[],filter='Alle',history=false,current=null;
function toast(t){const n=$('#toast');n.textContent=t;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2400)}
async function request(url,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(opts.method&&opts.method!=='GET')headers['X-CSRF-Token']=csrf;const r=await fetch(url,{...opts,headers});let data={};try{data=await r.json()}catch{}if(!r.ok){if(r.status===401){$('#loginWall').hidden=false}throw new Error(data.error||'Die Anfrage ist fehlgeschlagen.')}if(data.csrf)csrf=data.csrf;return data}
function setView(isHistory){history=isHistory;$('.navlink[data-view="orders"]').classList.toggle('active',!history);$('.navlink[data-view="history"]').classList.toggle('active',history);$('#barSection').textContent=history?'Verlauf':'Bestellungen';$('#pageTitle').textContent=history?'Bestellverlauf.':'Bestellungen im Blick.';$('#pageSub').textContent=history?'Alle Eingänge und Änderungen auf einen Blick.':'Eingänge prüfen, zusammenstellen und für die Abholung vorbereiten.';filter='Alle';document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.status==='Alle'));render()}
function render(){const q=$('#search').value.trim().toLocaleLowerCase('de');let list=orders.filter(o=>(filter==='Alle'||o.status===filter)&&(!q||[o.id,o.customerName,o.email,o.childName,o.childClass,...(o.items||[]).map(i=>i.name)].join(' ').toLocaleLowerCase('de').includes(q)));if(!history)list=list.filter(o=>o.status!=='Storniert');$('#orderRows').innerHTML=list.map(o=>{const count=(o.items||[]).reduce((s,i)=>s+Number(i.qty||1),0),statusClass=o.status==='In Bearbeitung'?'work':o.status==='Abgeschlossen'?'done':o.status==='Storniert'?'cancel':'',pickup=o.delivery==='child'?'Übergabe: '+(o.childName||'')+(o.childClass?' · '+o.childClass:''):o.delivery==='other'?'Abholung nach Absprache':'';const choices=['Offen','In Bearbeitung','Abgeschlossen','Storniert'].map(s=>'<option '+(o.status===s?'selected':'')+'>'+s+'</option>').join('');return '<tr><td><span class="id">'+esc(o.id)+'</span><span class="sub">'+new Date(o.date).toLocaleDateString('de-DE')+'</span></td><td><span class="customer">'+esc(o.customerName)+'</span><span class="sub">'+esc(o.email)+'</span><span class="sub">'+esc(pickup)+'</span></td><td>'+count+' Artikel<span class="sub">'+(o.items||[]).slice(0,2).map(i=>esc(i.name)+(i.qty>1?' ×'+i.qty:'')).join(', ')+(o.items?.length>2?' …':'')+'</span></td><td><span class="badge '+statusClass+'">'+esc(o.status)+'</span></td><td><span class="badge '+(o.paid?'paid':'unpaid')+'">'+(o.paid?'Bezahlt':'Offen')+'</span></td><td><b>'+money(o.total)+'</b></td><td><div class="actions"><button class="iconbtn" data-detail="'+esc(o.id)+'" title="Details ansehen" aria-label="Details ansehen">⌕</button><button class="iconbtn" data-print="'+esc(o.id)+'" title="Bestellzettel drucken" aria-label="Bestellzettel drucken">▤</button><button class="iconbtn" data-paid="'+esc(o.id)+'" title="Zahlung '+(o.paid?'öffnen':'als bezahlt markieren')+'" aria-label="Zahlung ändern">'+(o.paid?'€✓':'€')+'</button><select class="status-select" data-status-for="'+esc(o.id)+'" aria-label="Status für '+esc(o.id)+'">'+choices+'</select></div></td></tr>'}).join('');$('#emptyState').hidden=list.length>0;$('#emptyState strong').textContent=list.length?'':'Hier ist noch Ruhe.';const filtered=orders.filter(o=>o.status!=='Storniert');$('#openCount').textContent=orders.filter(o=>o.status==='Offen').length;$('#progressCount').textContent=orders.filter(o=>o.status==='In Bearbeitung').length;$('#doneCount').textContent=orders.filter(o=>o.status==='Abgeschlossen').length;$('#revenue').textContent=money(orders.filter(o=>o.status==='Abgeschlossen'&&o.paid).reduce((s,o)=>s+Number(o.total||0),0));}
async function refresh(){try{const d=await request('/api/admin/orders');orders=d.orders||[];$('#errorline').hidden=true;render();}catch(e){$('#errorline').textContent=e.message;$('#errorline').hidden=false}}
async function update(id,values){try{await request('/api/admin/orders/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify(values)});await refresh();toast('Bestellung aktualisiert.')}catch(e){toast(e.message)}}
function showOrder(o){if(!o)return;current=o;$('#detailTitle').textContent=o.id;const items=(o.items||[]).map(i=>'<div class="detailitem"><span>'+esc(i.name)+'<small>'+esc([i.colorName||i.color,i.size].filter(Boolean).join(' · ')||'Ohne Variante')+'</small></span><b>'+Number(i.qty||1)+' × '+money(i.price)+'</b></div>').join('');const pickup=o.delivery==='child'?'Übergabe über '+esc(o.childName)+' · Klasse '+esc(o.childClass):o.delivery==='other'?'Abholung: '+esc(o.otherPickup):'Abholung nach Absprache';$('#detailBody').innerHTML='<section class="detailgroup"><h3>Kundendaten</h3><p><b>'+esc(o.customerName)+'</b><br>'+esc(o.email)+'<br>'+pickup+'</p></section><section class="detailgroup"><h3>Artikel</h3>'+items+'<div class="detailitem"><b>Gesamt</b><b>'+money(o.total)+'</b></div></section><section class="detailgroup"><h3>Zahlung & Bearbeitung</h3><p>'+ (o.payment==='transfer'?'Überweisung':'Barzahlung')+' · '+(o.paid?'Bezahlt':'Noch offen')+'<br>Status: '+esc(o.status)+'<br>Eingegangen: '+new Date(o.date).toLocaleString('de-DE')+'</p></section><section class="detailgroup"><h3>Hinweis</h3><p>'+esc(o.note||'Kein zusätzlicher Hinweis.')+'</p></section>';$('#drawer').classList.add('open');$('#drawerBg').classList.add('open')}
function closeDrawer(){$('#drawer').classList.remove('open');$('#drawerBg').classList.remove('open')}
function exportCsv(){const rows=[['Bestellnummer','Datum','Kunde','E-Mail','Artikel','Status','Zahlung','Bezahlt','Gesamt'],...orders.map(o=>[o.id,new Date(o.date).toLocaleString('de-DE'),o.customerName,o.email,(o.items||[]).map(i=>`${i.name} ${i.colorName||''} ${i.size||''} ×${i.qty}`).join(' | '),o.status,o.payment==='transfer'?'Überweisung':'Barzahlung',o.paid?'Ja':'Nein',Number(o.total||0).toFixed(2)])];const csv='\ufeff'+rows.map(row=>row.map(v=>{let s=String(v??'');if(/^\s*[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}).join(';')).join('\r\n');const a=document.createElement('a'),u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.href=u;a.download='schoolstore-bestellungen.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function init(){try{const s=await fetch('/api/admin/session').then(r=>r.json());csrf=s.csrf||'';if(s.authenticated){$('#loginWall').hidden=true;await refresh()}else $('#loginWall').hidden=false;}catch{$('#loginWall').hidden=false;$('#loginError').textContent='Backend nicht erreichbar. Bitte Server starten und Seite neu laden.'}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const b=e.currentTarget.querySelector('button');b.disabled=true;try{const d=await request('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});csrf=d.csrf;$('#password').value='';$('#loginWall').hidden=true;await refresh();}catch(err){$('#loginError').textContent=err.message}finally{b.disabled=false}});
$('#logout').addEventListener('click',async()=>{try{await request('/api/admin/logout',{method:'POST',body:'{}'})}catch{}$('#loginWall').hidden=false;orders=[];render()});$('#refresh').addEventListener('click',refresh);$('#csv').addEventListener('click',exportCsv);$('#csvSmall').addEventListener('click',exportCsv);$('#search').addEventListener('input',render);
document.querySelectorAll('.navlink[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view==='history')));document.querySelector('.tabs').addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(!b)return;filter=b.dataset.status;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));render()});
$('#orderRows').addEventListener('click',e=>{const d=e.target.closest('[data-detail]'),p=e.target.closest('[data-print]'),paid=e.target.closest('[data-paid]');if(d)showOrder(orders.find(o=>o.id===d.dataset.detail));if(p){const o=orders.find(o=>o.id===p.dataset.print);window.printSchoolstorePackingSlip(o)}if(paid){const o=orders.find(o=>o.id===paid.dataset.paid);update(o.id,{paid:!o.paid})}});$('#orderRows').addEventListener('change',e=>{const s=e.target.closest('[data-status-for]');if(s)update(s.dataset.statusFor,{status:s.value})});$('#drawerClose').addEventListener('click',closeDrawer);$('#detailClose').addEventListener('click',closeDrawer);$('#drawerBg').addEventListener('click',closeDrawer);$('#detailPrint').addEventListener('click',()=>window.printSchoolstorePackingSlip(current));setInterval(()=>{if($('#loginWall').hidden)refresh()},30000);init();
})();
