import http from 'node:http';
import { readFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, extname, normalize, relative, isAbsolute, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes, scryptSync, timingSafeEqual, createHash } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';

const ROOT = fileURLToPath(new URL('.', import.meta.url));
const envPath = resolve(ROOT, '.env');
if (existsSync(envPath)) for (const raw of readFileSync(envPath, 'utf8').split(/\r?\n/)) {
  const line = raw.trim(); if (!line || line.startsWith('#')) continue;
  const at = line.indexOf('='); if (at > 0 && !process.env[line.slice(0, at).trim()]) process.env[line.slice(0, at).trim()] = line.slice(at + 1).trim();
}
const PORT = Number(process.env.PORT || 8766);
const HOST = process.env.HOST || '0.0.0.0';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || '';
if (ADMIN_PASSWORD.length < 12) { console.error('ADMIN_PASSWORD fehlt oder ist zu kurz. In Render als Secret (mindestens 12 Zeichen) setzen; lokal setup.ps1 ausführen.'); process.exit(1); }

const products = [
  { id:'shirt', name:'T-Shirt', category:'Textilien', price:17.95, colors:['Nebelblau','Hellgrau','Weiß','Schwarz','Navy','Beige'], colorValues:['#a3b4c4','#d3d3d3','#ffffff','#202020','#5a7a9c','#f5d7b2'], sizes:['8/10','12/14','S','M','L','XL','3XL'], available:true },
  { id:'hoodie', name:'Hoodie', category:'Textilien', price:38, colors:['Schwarz','Hellgrau'], colorValues:['#202020','#d3d3d3'], sizes:['S','M','L'], available:true },
  { id:'ziphoodie', name:'Zip-Hoodie', category:'Textilien', price:40, colors:['Schwarz','Hellgrau'], colorValues:['#202020','#d3d3d3'], sizes:['S','M','L'], available:true },
  { id:'mug', name:'Tasse', category:'Accessoires', price:4.5, colors:[], colorValues:[], sizes:[], available:true },
  { id:'starter', name:'Starterpaket', category:'Starterpakete', price:null, colors:[], colorValues:[], sizes:[], available:false },
  { id:'starterplus', name:'Starterpaket+', category:'Starterpakete', price:null, colors:[], colorValues:[], sizes:[], available:false }
];
const productById = new Map(products.map(p => [p.id,p]));
const dataDir = resolve(ROOT,'data'); mkdirSync(dataDir,{recursive:true});
const db = new DatabaseSync(resolve(dataDir,'schoolstore.sqlite'));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, created_at TEXT NOT NULL, customer_name TEXT NOT NULL, email TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'Offen', paid INTEGER NOT NULL DEFAULT 0, total REAL NOT NULL, payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS roles (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, permissions TEXT NOT NULL, system INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL COLLATE NOCASE UNIQUE, email TEXT NOT NULL COLLATE NOCASE UNIQUE, display_name TEXT NOT NULL, password_salt BLOB NOT NULL, password_hash BLOB NOT NULL, role_id TEXT NOT NULL REFERENCES roles(id), active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS invites (token_hash TEXT PRIMARY KEY, role_id TEXT NOT NULL REFERENCES roles(id), created_by INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL, expires_at TEXT NOT NULL, max_uses INTEGER NOT NULL, uses INTEGER NOT NULL DEFAULT 0, revoked INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS inventory (product_id TEXT NOT NULL, color_name TEXT NOT NULL DEFAULT '', size TEXT NOT NULL DEFAULT '', quantity INTEGER NOT NULL DEFAULT 0, tracked INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL, PRIMARY KEY(product_id,color_name,size));
CREATE TABLE IF NOT EXISTS custom_products (id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, price REAL NOT NULL, colors TEXT NOT NULL DEFAULT '[]', color_values TEXT NOT NULL DEFAULT '[]', sizes TEXT NOT NULL DEFAULT '[]', available INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activity_log (id INTEGER PRIMARY KEY AUTOINCREMENT, created_at TEXT NOT NULL, actor_id INTEGER, actor_name TEXT NOT NULL, role_name TEXT NOT NULL, action TEXT NOT NULL, details TEXT NOT NULL DEFAULT '');`);
for (const row of db.prepare('SELECT * FROM custom_products ORDER BY created_at').all()) products.push({id:row.id,name:row.name,category:row.category,price:Number(row.price),colors:JSON.parse(row.colors),colorValues:JSON.parse(row.color_values),sizes:JSON.parse(row.sizes),available:Boolean(row.available)});
productById.clear(); for (const product of products) productById.set(product.id,product);
const allStockVariants=()=>products.filter(p=>p.available).flatMap(p=>{const colors=p.colors.length?p.colors:[''],sizes=p.sizes.length?p.sizes:[''];return colors.flatMap(colorName=>sizes.map(size=>({product_id:p.id,color_name:colorName,size})));});
const seedStock=()=>{const now=new Date().toISOString(),put=db.prepare("INSERT OR IGNORE INTO inventory(product_id,color_name,size,quantity,tracked,updated_at) VALUES(?,?,?,0,1,?)");for(const item of allStockVariants())put.run(item.product_id,item.color_name,item.size,now);};
seedStock();
db.exec('UPDATE inventory SET tracked=1');
const insertOrder = db.prepare('INSERT INTO orders (id,created_at,customer_name,email,status,paid,total,payload) VALUES (?,?,?,?,?,?,?,?)');
const sessions = new Map(), attempts = new Map();
const permissions = [
  {id:'orders.view',label:'Bestellungen und Archiv ansehen',group:'Bestellungen'},
  {id:'orders.archive',label:'Archiv abgeschlossener und stornierter Bestellungen ansehen',group:'Bestellungen'},
  {id:'orders.status',label:'Bestellstatus ändern',group:'Bestellungen'},
  {id:'orders.payment',label:'Zahlungsstatus ändern',group:'Bestellungen'},
  {id:'orders.print',label:'Bestellzettel drucken',group:'Bestellungen'},
  {id:'orders.export',label:'Bestellungen als CSV exportieren',group:'Bestellungen'},
  {id:'audit.view',label:'Aktivitätsprotokoll ansehen',group:'Verwaltung'},
  {id:'stock.view',label:'Lagerbestand ansehen',group:'Lagerbestand'},
  {id:'stock.manage',label:'Bestände setzen und Lagerführung ändern',group:'Lagerbestand'},
  {id:'stock.products',label:'Neue Shop-Produkte hinzufügen',group:'Lagerbestand'},
  {id:'team.view',label:'Team und Rollen ansehen',group:'Team & Rollen'},
  {id:'team.invites',label:'Registrierungslinks erstellen und sperren',group:'Team & Rollen'},
  {id:'team.users',label:'Teamzugänge aktivieren und sperren',group:'Team & Rollen'},
  {id:'team.roles',label:'Rollen und Dashboard-Rechte verwalten',group:'Team & Rollen'},
  {id:'system.admin',label:'Administrator – Zugriff auf alle Verwaltungsbereiche',group:'Verwaltung'}
];
const allPermissionIds=permissions.map(p=>p.id),hashPassword=password=>{const salt=randomBytes(16);return {salt,hash:scryptSync(password,salt,64)}};
const permissionList=value=>{try{const parsed=JSON.parse(value||'[]');return Array.isArray(parsed)?parsed.filter(p=>typeof p==='string'):[]}catch{return [];}};
const effectivePermissions=user=>{const granted=new Set(permissionList(user?.permissions));if(['orders.status','orders.payment','orders.print','orders.export'].some(p=>granted.has(p)))granted.add('orders.view');if(granted.has('stock.manage')||granted.has('stock.products'))granted.add('stock.view');if(user?.role_id==='administrator'||granted.has('system.admin'))return [...new Set([...allPermissionIds,'system.admin'])];return [...granted];};
const audit=(actor,action,details='',fallback='Shop')=>db.prepare('INSERT INTO activity_log(created_at,actor_id,actor_name,role_name,action,details) VALUES(?,?,?,?,?,?)').run(new Date().toISOString(),actor?.id??null,actor?.display_name||fallback,actor?.role_name||actor?.roleName||'Shop',action,String(details).slice(0,500));
const auditSafely=(...args)=>{try{audit(...args)}catch(error){console.error('Aktivitätsprotokoll konnte nicht geschrieben werden:',error)}};
const rootRole=db.prepare('SELECT id FROM roles WHERE id=?').get('administrator');
if(!rootRole)db.prepare('INSERT INTO roles(id,name,permissions,system) VALUES(?,?,?,1)').run('administrator','Administrator',JSON.stringify(allPermissionIds));
else db.prepare('UPDATE roles SET name=?,permissions=?,system=1 WHERE id=?').run('Administrator',JSON.stringify(allPermissionIds),'administrator');
if(Number(db.prepare('SELECT COUNT(*) n FROM users').get().n)===0){const cred=hashPassword(ADMIN_PASSWORD);db.prepare('INSERT INTO users(username,email,display_name,password_salt,password_hash,role_id,active,created_at) VALUES(?,?,?,?,?,?,1,?)').run('admin','admin@schoolstore.local','Administrator',cred.salt,cred.hash,'administrator',new Date().toISOString());console.log('Erster Zugang erstellt: Benutzername admin · E-Mail admin@schoolstore.local');}
const mime = {'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon','.txt':'text/plain; charset=utf-8'};
const json = (res, status, data, headers={}) => { res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}); res.end(JSON.stringify(data)); };
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(s=>s.trim()).filter(Boolean).map(s=>{const i=s.indexOf('=');let value=s.slice(i+1);try{value=decodeURIComponent(value)}catch{}return [s.slice(0,i),value]}));}
function session(req,res){const c=cookies(req),id=c.schoolstore_session;let s=id&&sessions.get(id);if(!s){const sid=randomBytes(32).toString('base64url');s={csrf:randomBytes(24).toString('base64url'),userId:null,created:Date.now()};sessions.set(sid,s);res.setHeader('Set-Cookie',`schoolstore_session=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${process.env.NODE_ENV==='production'?'; Secure':''}`);return {id:sid,...s};}return {id,...s};}
function validCsrf(req,s){return req.headers['x-csrf-token']===s.csrf;}
function account(userId){return userId?db.prepare('SELECT u.id,u.username,u.email,u.display_name,u.role_id,u.active,r.name AS role_name,r.permissions,r.system FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=?').get(userId):null;}
function access(req,res,permission,write=false){const s=session(req,res);if(!s.userId){json(res,401,{error:'Bitte anmelden.'});return null;}const user=account(s.userId);if(!user||!user.active){sessions.delete(s.id);json(res,401,{error:'Dieser Teamzugang ist gesperrt.'});return null;}const allowed=effectivePermissions(user);if(permission&&!allowed.includes(permission)){json(res,403,{error:'Für diese Aktion fehlt dir die passende Berechtigung.'});return null;}if(write&&!validCsrf(req,s)){json(res,403,{error:'Sitzung abgelaufen. Bitte Seite neu laden.'});return null;}return {session:s,user,permissions:allowed};}
async function body(req){let raw='';for await(const part of req){raw+=part;if(raw.length>150000)throw new Error('Anfrage zu groß');}return raw?JSON.parse(raw):{};}
function getOrder(row){return {...JSON.parse(row.payload),id:row.id,date:row.created_at,status:row.status,paid:Boolean(row.paid),total:Number(row.total)};}
function orderRows(){return db.prepare('SELECT * FROM orders ORDER BY created_at DESC').all().map(getOrder);}
function sendOrder(req,res){
  const sid=cookies(req).schoolstore_session||req.socket.remoteAddress||'unknown';const now=Date.now(),recent=(attempts.get(sid)||[]).filter(t=>now-t<60000);if(recent.length>=8){json(res,429,{error:'Bitte warte kurz und versuche es erneut.'});return;}recent.push(now);attempts.set(sid,recent);
  body(req).then(input=>{
    const name=String(input.name||'').trim(),email=String(input.email||'').trim();if(name.length<2||name.length>120||!/^\S+@\S+\.\S+$/.test(email)||email.length>254)throw new Error('Bitte prüfe Name und E-Mail-Adresse.');
    if(input.delivery!=='child'&&input.delivery!=='other')throw new Error('Bitte wähle eine Abholung.');
    if(input.delivery==='child'&&(!String(input.childName||'').trim()||!String(input.childClass||'').trim()))throw new Error('Bitte ergänze Name und Klasse des Kindes.');
    if(input.delivery==='other'&&!String(input.otherPickup||'').trim())throw new Error('Bitte beschreibe die gewünschte Abholung.');
    if(!['transfer','cash'].includes(input.payment))throw new Error('Bitte wähle eine Zahlungsart.');
    if(!Array.isArray(input.items)||input.items.length<1||input.items.length>30)throw new Error('Der Warenkorb ist leer oder ungültig.');
    const items=input.items.map(line=>{const p=productById.get(String(line.id));const qty=Math.floor(Number(line.qty));if(!p?.available||!Number.isFinite(qty)||qty<1||qty>30)throw new Error('Ein Artikel ist nicht verfügbar.');const colorName=p.colors.length?String(line.colorName||''):'';const size=p.sizes.length?String(line.size||''):'';if(p.colors.length&&!p.colors.includes(colorName))throw new Error('Bitte prüfe die Farbwahl.');if(p.sizes.length&&!p.sizes.includes(size))throw new Error('Bitte prüfe die Größenwahl.');return {id:p.id,name:p.name,price:p.price,qty,colorName,color:p.colorValues[p.colors.indexOf(colorName)]||'',size};});
    const id='HGW-'+new Date().getFullYear()+'-'+randomBytes(3).toString('hex').toUpperCase(),date=new Date().toISOString(),total=Math.round(items.reduce((sum,x)=>sum+x.price*x.qty,0)*100)/100;
    const order={id,date,customerName:name,email,payment:input.payment,delivery:input.delivery,childName:String(input.childName||'').trim(),childClass:String(input.childClass||'').trim(),otherPickup:String(input.otherPickup||'').trim(),note:String(input.note||'').trim().slice(0,1000),items,total,status:'Offen',paid:false};
    db.exec('BEGIN IMMEDIATE');try{const reserved=new Map(),stockQuery=db.prepare('SELECT quantity,tracked FROM inventory WHERE product_id=? AND color_name=? AND size=?');for(const item of items){const key=[item.id,item.colorName,item.size].join('\u001f'),stock=stockQuery.get(item.id,item.colorName,item.size);item.stockReserved=Boolean(stock?.tracked);if(stock?.tracked){const available=Number(stock.quantity)-Number(reserved.get(key)||0);if(available<item.qty)throw new Error(`Für ${item.name} (${item.colorName||'Standard'}${item.size?' · '+item.size:''}) sind nur ${Math.max(0,available)} Stück auf Lager.`);reserved.set(key,Number(reserved.get(key)||0)+item.qty);}}for(const [key,qty] of reserved){const [productId,colorName,size]=key.split('\u001f');db.prepare('UPDATE inventory SET quantity=quantity-?,updated_at=? WHERE product_id=? AND color_name=? AND size=? AND tracked=1').run(qty,date,productId,colorName,size);}insertOrder.run(id,date,name,email,'Offen',0,total,JSON.stringify(order));db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}audit(null,'Neue Bestellung',`${id} · ${name}`,`Kunde: ${name}`);json(res,201,{order});
  }).catch(err=>json(res,400,{error:err.message||'Bestellung konnte nicht gespeichert werden.'}));
}
const server=http.createServer(async(req,res)=>{
  try{
    const url=new URL(req.url,'http://localhost');
    if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true});
    if(req.method==='GET'&&url.pathname==='/api/catalog')return json(res,200,{products:products.filter(p=>p.available)});
    if(req.method==='GET'&&url.pathname==='/api/admin/session'){const s=session(req,res),user=account(s.userId);if(user?.active)return json(res,200,{authenticated:true,csrf:s.csrf,user:{id:user.id,username:user.username,email:user.email,displayName:user.display_name,roleId:user.role_id,roleName:user.role_name,systemAdmin:user.role_id==='administrator',adminAccess:user.role_id==='administrator'||permissionList(user.permissions).includes('system.admin')},permissions:effectivePermissions(user)});return json(res,200,{authenticated:false,csrf:s.csrf});}
    if(req.method==='POST'&&url.pathname==='/api/orders')return sendOrder(req,res);
    if(req.method==='POST'&&url.pathname==='/api/admin/login'){
      const s=session(req,res);if(!validCsrf(req,s))return json(res,403,{error:'Seite bitte neu laden.'});
      const ip=req.socket.remoteAddress||'unknown',a=(attempts.get(ip)||[]).filter(t=>Date.now()-t<60000);if(a.length>=6)return json(res,429,{error:'Zu viele Anmeldeversuche. Bitte später erneut versuchen.'});a.push(Date.now());attempts.set(ip,a);
      const input=await body(req),identity=String(input.identity||input.username||input.email||'').trim(),user=db.prepare('SELECT * FROM users WHERE username=? OR email=?').get(identity,identity);if(!user?.active)return json(res,401,{error:'Anmeldung nicht möglich. Bitte Zugangsdaten prüfen.'});const candidate=scryptSync(String(input.password||''),user.password_salt,64),storedHash=user.password_hash;if(!storedHash||candidate.byteLength!==storedHash.byteLength||!timingSafeEqual(candidate,storedHash))return json(res,401,{error:'Anmeldung nicht möglich. Bitte Zugangsdaten prüfen.'});
      const profile=account(user.id);if(!profile?.active)return json(res,401,{error:'Dein Teamzugang ist nicht mehr aktiv. Bitte wende dich an den Administrator.'});const resolvedPermissions=effectivePermissions(profile);
      sessions.delete(s.id);const sid=randomBytes(32).toString('base64url'),fresh={csrf:randomBytes(24).toString('base64url'),userId:user.id,created:Date.now()};sessions.set(sid,fresh);auditSafely(profile,'Anmeldung','Erfolgreich');return json(res,200,{authenticated:true,csrf:fresh.csrf,user:{id:user.id,username:user.username,email:user.email,displayName:user.display_name,roleId:user.role_id,roleName:user.role_name,systemAdmin:user.role_id==='administrator',adminAccess:user.role_id==='administrator'||permissionList(user.permissions).includes('system.admin')},permissions:resolvedPermissions},{'Set-Cookie':`schoolstore_session=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${process.env.NODE_ENV==='production'?'; Secure':''}`});
    }
    if(req.method==='POST'&&url.pathname==='/api/admin/register'){const publicSession=session(req,res);if(!validCsrf(req,publicSession))return json(res,403,{error:'Seite bitte neu laden.'});const ip=req.socket.remoteAddress||'unknown',a=(attempts.get('register:'+ip)||[]).filter(t=>Date.now()-t<60000);if(a.length>=8)return json(res,429,{error:'Zu viele Registrierungsversuche. Bitte kurz warten.'});a.push(Date.now());attempts.set('register:'+ip,a);const input=await body(req),token=String(input.token||''),username=String(input.username||'').trim().toLowerCase(),email=String(input.email||'').trim().toLowerCase(),displayName=String(input.displayName||'').trim(),password=String(input.password||'');if(!/^[a-z0-9._-]{3,32}$/.test(username))return json(res,400,{error:'Der Benutzername muss 3–32 Zeichen lang sein und darf Buchstaben, Zahlen, Punkt, Strich und Unterstrich enthalten.'});if(displayName.length<2||displayName.length>100||email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json(res,400,{error:'Bitte prüfe Name und E-Mail-Adresse.'});if(password.length<12||password.length>200)return json(res,400,{error:'Das Passwort muss mindestens 12 Zeichen lang sein.'});if(token.length<30||token.length>128)return json(res,400,{error:'Dieser Registrierungslink ist ungültig.'});const tokenHash=createHash('sha256').update(token).digest('hex'),invite=db.prepare('SELECT * FROM invites WHERE token_hash=? AND revoked=0').get(tokenHash);if(!invite||new Date(invite.expires_at).getTime()<Date.now()||invite.uses>=invite.max_uses)return json(res,410,{error:'Dieser Registrierungslink ist abgelaufen oder bereits verwendet.'});const cred=hashPassword(password);let transactionOpen=false;try{db.exec('BEGIN IMMEDIATE');transactionOpen=true;const current=db.prepare('SELECT * FROM invites WHERE token_hash=? AND revoked=0').get(tokenHash);if(!current||new Date(current.expires_at).getTime()<Date.now())throw new Error('Dieser Registrierungslink ist nicht mehr gültig.');if(current.uses>=current.max_uses)throw new Error('Dieser Registrierungslink ist nicht mehr gültig.');const result=db.prepare('INSERT INTO users(username,email,display_name,password_salt,password_hash,role_id,active,created_at) VALUES(?,?,?,?,?,?,1,?)').run(username,email,displayName,cred.salt,cred.hash,current.role_id,new Date().toISOString());db.prepare('UPDATE invites SET uses=uses+1 WHERE token_hash=?').run(tokenHash);db.exec('COMMIT');transactionOpen=false;auditSafely(account(Number(result.lastInsertRowid)),'Zugang registriert','Konto erstellt');return json(res,201,{ok:true,userId:Number(result.lastInsertRowid)});}catch(error){if(transactionOpen)try{db.exec('ROLLBACK')}catch{}if(String(error.message).includes('UNIQUE constraint failed'))return json(res,409,{error:'Benutzername oder E-Mail-Adresse wird bereits verwendet.'});if(String(error.message).includes('Registrierungslink'))return json(res,410,{error:error.message});throw error;}}
    if(req.method==='POST'&&url.pathname==='/api/admin/logout'){const auth=access(req,res,null,true);if(!auth)return;audit(auth.user,'Abmeldung','Sitzung beendet');sessions.delete(auth.session.id);res.setHeader('Set-Cookie','schoolstore_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true});}
    if(req.method==='GET'&&url.pathname==='/api/admin/activity'){const auth=access(req,res,'audit.view');if(!auth)return;const rows=db.prepare('SELECT created_at,actor_name,role_name,action,details FROM activity_log ORDER BY id DESC LIMIT 200').all();return json(res,200,{items:rows});}
    const orderAction=url.pathname.match(/^\/api\/admin\/orders\/([^/]+)\/(view|print)$/);if(orderAction&&req.method==='POST'){const id=decodeURIComponent(orderAction[1]),row=db.prepare('SELECT * FROM orders WHERE id=?').get(id);if(!row)return json(res,404,{error:'Bestellung nicht gefunden.'});const required=orderAction[2]==='print'?'orders.print':(['Abgeschlossen','Storniert'].includes(row.status)?'orders.archive':'orders.view'),auth=access(req,res,required,true);if(!auth)return;audit(auth.user,orderAction[2]==='print'?'Bestellzettel gedruckt':'Bestellung angesehen',id);return json(res,200,{order:getOrder(row)});}
    if(req.method==='POST'&&url.pathname==='/api/admin/export'){const auth=access(req,res,'orders.export',true);if(!auth)return;audit(auth.user,'Bestellungen exportiert','CSV-Datei heruntergeladen');return json(res,200,{ok:true});}
    if(url.pathname==='/api/admin/orders'&&req.method==='GET'){const archive=url.searchParams.get('view')==='archive',auth=access(req,res,archive?'orders.archive':'orders.view');if(!auth)return;const all=orderRows(),orders=all.filter(o=>archive?['Abgeschlossen','Storniert'].includes(o.status):!['Abgeschlossen','Storniert'].includes(o.status));const stats=auth.permissions.includes('orders.view')?{open:all.filter(o=>o.status==='Offen').length,progress:all.filter(o=>o.status==='In Bearbeitung').length,done:all.filter(o=>o.status==='Abgeschlossen').length,revenue:all.filter(o=>o.status==='Abgeschlossen'&&o.paid).reduce((n,o)=>n+o.total,0)}:null;return json(res,200,{orders,stats});}
    const match=url.pathname.match(/^\/api\/admin\/orders\/([^/]+)$/);
    if(match&&req.method==='PATCH'){const id=decodeURIComponent(match[1]),existing=db.prepare('SELECT * FROM orders WHERE id=?').get(id);if(!existing)return json(res,404,{error:'Bestellung nicht gefunden.'});const input=await body(req),status=input.status===undefined?existing.status:String(input.status),paid=input.paid===undefined?Boolean(existing.paid):Boolean(input.paid);let actor=null;if(status!==existing.status){if(!['Offen','In Bearbeitung','Abgeschlossen','Storniert'].includes(status))return json(res,400,{error:'Ungültiger Status.'});actor=access(req,res,'orders.status',true);if(!actor)return;}if(paid!==Boolean(existing.paid)){actor=access(req,res,'orders.payment',true);if(!actor)return;}if(status===existing.status&&paid===Boolean(existing.paid))return json(res,400,{error:'Es wurde keine Änderung angegeben.'});let payload=JSON.parse(existing.payload);db.exec('BEGIN IMMEDIATE');try{if(status==='Storniert'&&existing.status!=='Storniert'){for(const item of payload.items||[])if(item.stockReserved)db.prepare('UPDATE inventory SET quantity=quantity+?,updated_at=? WHERE product_id=? AND color_name=? AND size=?').run(Number(item.qty)||0,new Date().toISOString(),item.id,item.colorName||'',item.size||'');}else if(existing.status==='Storniert'&&status!=='Storniert'){const reserved=new Map(),query=db.prepare('SELECT quantity,tracked FROM inventory WHERE product_id=? AND color_name=? AND size=?');for(const item of payload.items||[]){const key=[item.id,item.colorName||'',item.size||''].join('\u001f'),stock=query.get(item.id,item.colorName||'',item.size||'');item.stockReserved=Boolean(stock?.tracked);if(stock?.tracked){const available=Number(stock.quantity)-Number(reserved.get(key)||0);if(available<(Number(item.qty)||0))throw new Error(`Nicht genug Lagerbestand für ${item.name}.`);reserved.set(key,Number(reserved.get(key)||0)+(Number(item.qty)||0));}}for(const [key,qty] of reserved){const [productId,colorName,size]=key.split('\u001f');db.prepare('UPDATE inventory SET quantity=quantity-?,updated_at=? WHERE product_id=? AND color_name=? AND size=? AND tracked=1').run(qty,new Date().toISOString(),productId,colorName,size);}}db.prepare('UPDATE orders SET status=?,paid=?,payload=? WHERE id=?').run(status,paid?1:0,JSON.stringify(payload),id);db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');if(error.message.includes('Lagerbestand'))return json(res,409,{error:error.message});throw error;}if(status!==existing.status)audit(actor.user,'Bestellstatus geändert',`${id}: ${existing.status} → ${status}`);if(paid!==Boolean(existing.paid))audit(actor.user,'Zahlungsstatus geändert',`${id}: ${paid?'als bezahlt markiert':'Zahlung wieder geöffnet'}`);return json(res,200,{order:getOrder(db.prepare('SELECT * FROM orders WHERE id=?').get(id))});}
    if(url.pathname==='/api/admin/stock'&&req.method==='GET'){const auth=access(req,res,'stock.view');if(!auth)return;seedStock();return json(res,200,{products:products.filter(p=>p.available),items:db.prepare('SELECT * FROM inventory ORDER BY product_id,color_name,size').all()});}
    if(url.pathname==='/api/admin/stock'&&req.method==='PUT'){const auth=access(req,res,'stock.manage',true);if(!auth)return;const input=await body(req),p=productById.get(String(input.productId||'')),colorName=p?.colors.length?String(input.colorName||''):'',size=p?.sizes.length?String(input.size||''):'';if(!p?.available||(p.colors.length&&!p.colors.includes(colorName))||(p.sizes.length&&!p.sizes.includes(size)))return json(res,400,{error:'Bitte prüfe Produkt, Farbe und Größe.'});const quantity=Number(input.quantity);if(!Number.isInteger(quantity)||quantity<0||quantity>100000)return json(res,400,{error:'Der Lagerbestand muss zwischen 0 und 100.000 liegen.'});const updatedAt=new Date().toISOString();db.prepare('INSERT INTO inventory(product_id,color_name,size,quantity,tracked,updated_at) VALUES(?,?,?,?,1,?) ON CONFLICT(product_id,color_name,size) DO UPDATE SET quantity=excluded.quantity,tracked=1,updated_at=excluded.updated_at').run(p.id,colorName,size,quantity,updatedAt);audit(auth.user,'Lagerbestand geändert',`${p.name}${colorName?' · '+colorName:''}${size?' · '+size:''}: ${quantity} Stück`);return json(res,200,{ok:true,item:{product_id:p.id,color_name:colorName,size,quantity,tracked:1,updated_at:updatedAt}});}
    if(url.pathname==='/api/admin/products'&&req.method==='POST'){const auth=access(req,res,'stock.products',true);if(!auth)return;const input=await body(req),name=String(input.name||'').trim(),category=String(input.category||'Textilien').trim(),price=Number(input.price),split=x=>[...new Set((Array.isArray(x)?x:String(x||'').split(',')).map(v=>String(v).trim()).filter(Boolean))].slice(0,20),colors=split(input.colors),sizes=split(input.sizes);if(name.length<2||name.length>80||category.length<2||category.length>40||!Number.isFinite(price)||price<0||price>10000||colors.some(x=>x.length>40)||sizes.some(x=>x.length>20))return json(res,400,{error:'Bitte prüfe Name, Kategorie, Preis, Farben und Größen.'});const id='custom_'+randomBytes(9).toString('hex'),colorValues=colors.map((_,i)=>['#6aaa28','#5b7898','#222222','#d6d6d6','#e0b88b'][i%5]),createdAt=new Date().toISOString(),product={id,name,category,price,colors,colorValues,sizes,available:true};db.prepare('INSERT INTO custom_products(id,name,category,price,colors,color_values,sizes,available,created_at) VALUES(?,?,?,?,?,?,?,1,?)').run(id,name,category,price,JSON.stringify(colors),JSON.stringify(colorValues),JSON.stringify(sizes),createdAt);products.push(product);productById.set(id,product);seedStock();audit(auth.user,'Shop-Produkt hinzugefügt',`${name} · ${price.toFixed(2)} €`);return json(res,201,{product});}
    if(url.pathname==='/api/admin/team'&&req.method==='GET'){const auth=access(req,res);if(!auth)return;if(!auth.permissions.some(p=>p.startsWith('team.')))return json(res,403,{error:'Keine Team-Berechtigung.'});const canRoles=auth.permissions.includes('team.roles'),canUsers=auth.permissions.includes('team.users'),canInvites=auth.permissions.includes('team.invites'),roleRows=db.prepare('SELECT id,name,permissions,system FROM roles ORDER BY system DESC,name').all();return json(res,200,{permissionCatalog:permissions,roles:roleRows.map(r=>({...r,isAdministrator:Boolean(r.system),hasAdminAccess:Boolean(r.system)||JSON.parse(r.permissions).includes('system.admin'),permissions:JSON.parse(r.permissions)})),users:canUsers?db.prepare('SELECT u.id,u.username,u.email,u.display_name,u.active,u.created_at,r.name AS role_name,r.id AS role_id,r.system,r.permissions FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.created_at').all().map(u=>({...u,isAdministrator:Boolean(u.system),hasAdminAccess:Boolean(u.system)||JSON.parse(u.permissions).includes('system.admin')})):null,invites:canInvites?db.prepare('SELECT i.token_hash,i.role_id,i.created_at,i.expires_at,i.max_uses,i.uses,i.revoked,r.name AS role_name,r.permissions FROM invites i JOIN roles r ON r.id=i.role_id ORDER BY i.created_at DESC LIMIT 100').all().map(i=>({...i,id:i.token_hash.slice(0,12)})):null,canRoles,canUsers,canInvites,isSystemAdmin:auth.user.role_id==='administrator'});}
    if(url.pathname==='/api/admin/roles'&&req.method==='POST'){const auth=access(req,res,'team.roles',true);if(!auth)return;const input=await body(req),name=String(input.name||'').trim(),allowed=new Set(allPermissionIds),granted=[...new Set(Array.isArray(input.permissions)?input.permissions.filter(p=>allowed.has(p)):[])];if(granted.includes('system.admin')&&auth.user.role_id!=='administrator')return json(res,403,{error:'Nur der Systemadministrator kann Administratorzugriff vergeben.'});if(name.toLocaleLowerCase('de')==='administrator')return json(res,400,{error:'Der Name Administrator ist für die geschützte Systemrolle reserviert.'});if(name.length<2||name.length>50)return json(res,400,{error:'Der Rollenname muss 2–50 Zeichen lang sein.'});const id='role_'+randomBytes(9).toString('hex');try{db.prepare('INSERT INTO roles(id,name,permissions,system) VALUES(?,?,?,0)').run(id,name,JSON.stringify(granted));}catch(error){if(String(error.message).includes('UNIQUE'))return json(res,409,{error:'Dieser Rollenname existiert bereits.'});throw error;}audit(auth.user,'Rolle erstellt',`${name} · ${granted.length} Rechte`);return json(res,201,{role:{id,name,permissions:granted,system:0}});}
    const roleMatch=url.pathname.match(/^\/api\/admin\/roles\/([^/]+)$/);if(roleMatch&&req.method==='PATCH'){const auth=access(req,res,'team.roles',true);if(!auth)return;const id=decodeURIComponent(roleMatch[1]),role=db.prepare('SELECT * FROM roles WHERE id=?').get(id);if(!role)return json(res,404,{error:'Rolle nicht gefunden.'});if(role.system)return json(res,403,{error:'Die Administrator-Rolle ist geschützt.'});if(JSON.parse(role.permissions).includes('system.admin')&&auth.user.role_id!=='administrator')return json(res,403,{error:'Nur der Systemadministrator kann Administratorrollen ändern.'});const input=await body(req),name=String(input.name??role.name).trim(),allowed=new Set(allPermissionIds),granted=Array.isArray(input.permissions)?[...new Set(input.permissions.filter(p=>allowed.has(p)))]:JSON.parse(role.permissions);if(granted.includes('system.admin')&&auth.user.role_id!=='administrator')return json(res,403,{error:'Nur der Systemadministrator kann Administratorzugriff vergeben.'});if(name.toLocaleLowerCase('de')==='administrator')return json(res,400,{error:'Der Name Administrator ist für die geschützte Systemrolle reserviert.'});if(name.length<2||name.length>50)return json(res,400,{error:'Der Rollenname muss 2–50 Zeichen lang sein.'});try{db.prepare('UPDATE roles SET name=?,permissions=? WHERE id=?').run(name,JSON.stringify(granted),id);}catch(error){if(String(error.message).includes('UNIQUE'))return json(res,409,{error:'Dieser Rollenname existiert bereits.'});throw error;}audit(auth.user,'Rolle geändert',name);return json(res,200,{ok:true});}
    if(roleMatch&&req.method==='DELETE'){const auth=access(req,res,'team.roles',true);if(!auth)return;const id=decodeURIComponent(roleMatch[1]),role=db.prepare('SELECT * FROM roles WHERE id=?').get(id);if(!role)return json(res,404,{error:'Rolle nicht gefunden.'});if(role.system)return json(res,403,{error:'Die Administrator-Rolle ist geschützt.'});if(JSON.parse(role.permissions).includes('system.admin')&&auth.user.role_id!=='administrator')return json(res,403,{error:'Nur der Systemadministrator kann Administratorrollen löschen.'});if(db.prepare('SELECT COUNT(*) n FROM users WHERE role_id=?').get(id).n||db.prepare('SELECT COUNT(*) n FROM invites WHERE role_id=? AND revoked=0 AND uses<max_uses').get(id).n)return json(res,409,{error:'Diese Rolle wird noch von Teamzugängen oder Einladungen verwendet.'});db.prepare('DELETE FROM roles WHERE id=?').run(id);audit(auth.user,'Rolle gelöscht',role.name);return json(res,200,{ok:true});}
    if(url.pathname==='/api/admin/invites'&&req.method==='POST'){const auth=access(req,res,'team.invites',true);if(!auth)return;const input=await body(req),roleId=String(input.roleId||''),role=db.prepare('SELECT id,system,permissions FROM roles WHERE id=?').get(roleId);if(!role||role.system)return json(res,400,{error:'Bitte wähle eine Teamrolle, keine Systemadministrator-Rolle.'});if(JSON.parse(role.permissions).includes('system.admin')&&auth.user.role_id!=='administrator')return json(res,403,{error:'Nur der Systemadministrator kann Administratorzugriff einladen.'});const hours=Math.max(1,Math.min(720,Math.floor(Number(input.expiresHours)||168))),maxUses=Math.max(1,Math.min(100,Math.floor(Number(input.maxUses)||1))),token=randomBytes(32).toString('base64url'),tokenHash=createHash('sha256').update(token).digest('hex'),createdAt=new Date(),expiresAt=new Date(createdAt.getTime()+hours*3600000).toISOString();db.prepare('INSERT INTO invites(token_hash,role_id,created_by,created_at,expires_at,max_uses,uses,revoked) VALUES(?,?,?,?,?,?,0,0)').run(tokenHash,roleId,auth.user.id,createdAt.toISOString(),expiresAt,maxUses);const roleName=db.prepare('SELECT name FROM roles WHERE id=?').get(roleId).name;audit(auth.user,'Registrierungslink erstellt',`${roleName} · ${maxUses} Registrierungen`);return json(res,201,{id:tokenHash.slice(0,12),path:'/registrieren.html?token='+token,expiresAt,maxUses,roleName});}
    const inviteMatch=url.pathname.match(/^\/api\/admin\/invites\/([^/]+)$/);if(inviteMatch&&req.method==='DELETE'){const auth=access(req,res,'team.invites',true);if(!auth)return;const id=decodeURIComponent(inviteMatch[1]);const result=db.prepare('UPDATE invites SET revoked=1 WHERE substr(token_hash,1,12)=? AND revoked=0').run(id);if(!result.changes)return json(res,404,{error:'Einladung nicht gefunden.'});audit(auth.user,'Registrierungslink gesperrt',id);return json(res,200,{ok:true});}
    const userMatch=url.pathname.match(/^\/api\/admin\/users\/([^/]+)$/);if(userMatch&&req.method==='PATCH'){const auth=access(req,res,'team.users',true);if(!auth)return;const id=Number(userMatch[1]),target=account(id);if(!target)return json(res,404,{error:'Teamzugang nicht gefunden.'});const input=await body(req),active=input.active===undefined?Boolean(target.active):Boolean(input.active),roleId=input.roleId===undefined?target.role_id:String(input.roleId);if(id===auth.user.id&&!active)return json(res,400,{error:'Du kannst deinen eigenen Zugang nicht sperren.'});if(target.role_id==='administrator'&&(roleId!==target.role_id||!active))return json(res,403,{error:'Der Systemadministrator-Zugang kann nicht geändert oder gesperrt werden.'});let newRoleName=target.role_name;if(roleId!==target.role_id){if(!auth.permissions.includes('team.roles'))return json(res,403,{error:'Zum Zuweisen einer Rolle fehlt die Berechtigung Rollen verwalten.'});if(id===auth.user.id)return json(res,400,{error:'Du kannst deine eigene Rolle nicht ändern.'});const newRole=db.prepare('SELECT id,system,permissions,name FROM roles WHERE id=?').get(roleId);if(!newRole||newRole.system)return json(res,400,{error:'Diese Rollenzuweisung ist nicht erlaubt.'});if(JSON.parse(newRole.permissions).includes('system.admin')&&auth.user.role_id!=='administrator')return json(res,403,{error:'Nur der Systemadministrator kann Administratorzugriff vergeben.'});newRoleName=newRole.name;}db.prepare('UPDATE users SET active=?,role_id=? WHERE id=?').run(active?1:0,roleId,id);audit(auth.user,'Teamzugang geändert',`${target.display_name} · ${active?'aktiv':'gesperrt'}${roleId!==target.role_id?' · Rolle: '+target.role_name+' → '+newRoleName:''}`);return json(res,200,{ok:true});}
    if(url.pathname.startsWith('/api/'))return json(res,404,{error:'Endpunkt nicht gefunden.'});
    const pathname=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname),file=normalize(resolve(ROOT,'.'+pathname)),rel=relative(ROOT,file);if(isAbsolute(rel)||rel==='..'||rel.startsWith('..'+sep)||rel.startsWith('data'+sep)||rel==='.env'||rel.startsWith('.env.'))return json(res,403,{error:'Zugriff verweigert.'});if(!existsSync(file))return json(res,404,{error:'Datei nicht gefunden.'});res.writeHead(200,{'Content-Type':mime[extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','X-Frame-Options':'DENY','Cache-Control':'no-cache'});res.end(readFileSync(file));
  }catch(err){console.error(err);if(!res.headersSent)json(res,500,{error:'Unerwarteter Serverfehler.'});}
});
server.listen(PORT,HOST,()=>console.log(`Schoolstore läuft auf http://localhost:${PORT} · Datenbank: ${resolve(dataDir,'schoolstore.sqlite')}`));
process.on('SIGINT',()=>{db.close();server.close(()=>process.exit(0));});
