(function(){
  'use strict';
  const CART_KEY='schoolstore-cart-v2';
  const products=[
    {id:'shirt',name:'T-Shirts',category:'Textilien',price:17.95,tag:'Viele Farben & Größen',description:'T-Shirt · 17,95 €',kind:'shirt',available:true,colors:['Nebelblau','Hellgrau','Weiß','Schwarz','Navy','Beige'],colorValues:['#a3b4c4','#d3d3d3','#ffffff','#202020','#5a7a9c','#f5d7b2'],sizes:['8/10','12/14','S','M','L','XL','3XL']},
    {id:'hoodie',name:'Hoodies',category:'Textilien',price:38,tag:'Bequem & warm',description:'Hoodie · 38,00 €',kind:'hoodie',available:true,colors:['Schwarz','Hellgrau'],colorValues:['#202020','#d3d3d3'],sizes:['S','M','L']},
    {id:'ziphoodie',name:'Zip-Hoodies',category:'Textilien',price:40,tag:'Mit Reißverschluss',description:'Zip-Hoodie · 40,00 €',kind:'zip',available:true,colors:['Schwarz','Hellgrau'],colorValues:['#202020','#d3d3d3'],sizes:['S','M','L']},
    {id:'mug',name:'Tassen',category:'Accessoires',price:4.5,tag:'Für Kaffee, Tee & Kakao',description:'Schoolstore-Tasse · 4,50 €',kind:'mug',available:true,colors:[],colorValues:[],sizes:[]},
    {id:'starter',name:'Starterpakete',category:'Starterpakete',price:null,tag:'Preis folgt',description:'Für den perfekten Schulstart',kind:'starter',available:false,colors:[],colorValues:[],sizes:[]},
    {id:'starterplus',name:'Starterpakete+',category:'Starterpakete',price:null,tag:'Preis folgt',description:'Erweiterte Ausstattung',kind:'starterplus',available:false,colors:[],colorValues:[],sizes:[]}
  ];
  const art={
    shirt:function(c){const k='tee'+String(c).replace(/\W/g,'');return `<svg viewBox="0 0 200 240" aria-hidden="true"><defs><linearGradient id="${k}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${c}"/><stop offset=".48" stop-color="${c}"/><stop offset="1" stop-color="#17251d" stop-opacity=".16"/></linearGradient><linearGradient id="${k}s" x1="0" x2="1"><stop stop-color="#fff" stop-opacity=".46"/><stop offset=".34" stop-color="#fff" stop-opacity=".04"/><stop offset="1" stop-color="#17251d" stop-opacity=".13"/></linearGradient></defs><ellipse cx="102" cy="222" rx="68" ry="9" fill="#233627" opacity=".1"/><path d="M68 27 38 39 15 78l31 14 13-20-2 136q43 13 86 0l-2-136 13 20 31-14-23-39-30-12c-5 18-16 30-32 30S73 45 68 27Z" fill="url(#${k})" stroke="#203025" stroke-opacity=".12" stroke-width="1.5"/><path d="M68 27 38 39 15 78l31 14 13-20-2 136q43 13 86 0l-2-136 13 20 31-14-23-39-30-12c-5 18-16 30-32 30S73 45 68 27Z" fill="url(#${k}s)"/><path d="M76 38q10 25 24 25t24-25" fill="none" stroke="#fff" stroke-opacity=".5" stroke-width="3"/><path d="M79 40q8 18 21 18t21-18" fill="none" stroke="#17251d" stroke-opacity=".15" stroke-width="1.5"/><path d="M55 77 44 89m101-12 11 12M59 207q41 11 82 0M61 100v94" fill="none" stroke="#17251d" stroke-opacity=".14" stroke-width="1.2"/><path d="M65 87v105" fill="none" stroke="#fff" stroke-opacity=".13" stroke-width="2"/></svg>`},
    hoodie:function(c){const k='hood'+String(c).replace(/\W/g,'');return `<svg viewBox="0 0 200 240" aria-hidden="true"><defs><linearGradient id="${k}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${c}"/><stop offset=".55" stop-color="${c}"/><stop offset="1" stop-color="#111b15" stop-opacity=".24"/></linearGradient><linearGradient id="${k}s"><stop stop-color="#fff" stop-opacity=".3"/><stop offset=".5" stop-color="#fff" stop-opacity=".02"/><stop offset="1" stop-color="#17251d" stop-opacity=".15"/></linearGradient></defs><ellipse cx="101" cy="220" rx="69" ry="9" fill="#233627" opacity=".11"/><path d="M67 53 39 65 17 92l13 112q70 20 140 0l13-112-22-27-28-12c-4 20-16 32-33 32S71 73 67 53Z" fill="url(#${k})" stroke="#17251d" stroke-opacity=".16" stroke-width="1.5"/><path d="M70 55q3-35 30-38 27 3 30 38-9 29-30 29T70 55Z" fill="url(#${k})" stroke="#17251d" stroke-opacity=".18" stroke-width="1.5"/><path d="M75 54q5-24 25-27 20 3 25 27M79 56q7 19 21 19t21-19" fill="none" stroke="#fff" stroke-opacity=".26" stroke-width="2"/><path d="M80 82v27m40-27v27" fill="none" stroke="#f2f3ed" stroke-opacity=".78" stroke-width="2"/><path d="M79 82 81 106m40-24-2 24" fill="none" stroke="#17251d" stroke-opacity=".25" stroke-width="1"/><path d="M63 91 37 100m100-9 26 9M31 193q69 17 138 0" fill="none" stroke="#17251d" stroke-opacity=".16" stroke-width="1.4"/><path d="M54 96v85m92-85v85" fill="none" stroke="#fff" stroke-opacity=".12" stroke-width="2"/><path d="M76 141q24 5 48 0l-5 30q-19 9-38 0Z" fill="#17251d" fill-opacity=".06" stroke="#fff" stroke-opacity=".22" stroke-width="1.4"/><path d="M100 84v25m-3-3h6" stroke="#17251d" stroke-opacity=".32" stroke-width="1.4"/></svg>`},
    zip:function(c){const k='zip'+String(c).replace(/\W/g,'');return `<svg viewBox="0 0 200 240" aria-hidden="true"><defs><linearGradient id="${k}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${c}"/><stop offset=".5" stop-color="${c}"/><stop offset="1" stop-color="#101a13" stop-opacity=".24"/></linearGradient><linearGradient id="${k}s"><stop stop-color="#fff" stop-opacity=".31"/><stop offset=".5" stop-color="#fff" stop-opacity=".02"/><stop offset="1" stop-color="#17251d" stop-opacity=".16"/></linearGradient></defs><ellipse cx="101" cy="220" rx="69" ry="9" fill="#233627" opacity=".11"/><path d="M67 53 39 65 17 92l13 112q70 20 140 0l13-112-22-27-28-12c-4 20-16 32-33 32S71 73 67 53Z" fill="url(#${k})" stroke="#17251d" stroke-opacity=".16" stroke-width="1.5"/><path d="M70 55q3-35 30-38 27 3 30 38-9 29-30 29T70 55Z" fill="url(#${k})" stroke="#17251d" stroke-opacity=".18" stroke-width="1.5"/><path d="M75 54q5-24 25-27 20 3 25 27M79 56q7 19 21 19t21-19" fill="none" stroke="#fff" stroke-opacity=".27" stroke-width="2"/><path d="M100 83v119" stroke="#f7f7f1" stroke-width="3"/><path d="M104 84v116" stroke="#17251d" stroke-opacity=".23" stroke-width="1"/><path d="M96 102h8m-8 9h8m-8 9h8m-8 9h8m-8 9h8m-8 9h8m-8 9h8m-8 9h8m-8 9h8" stroke="#fff" stroke-opacity=".7" stroke-width="1"/><path d="M76 140q11 4 19 1l-2 27q-8 8-19 5Z" fill="#17251d" fill-opacity=".06" stroke="#fff" stroke-opacity=".22"/><path d="M105 141q13 4 19 0l2 32q-12 5-22-5Z" fill="#17251d" fill-opacity=".06" stroke="#fff" stroke-opacity=".22"/><path d="M63 91 37 100m100-9 26 9M31 193q69 17 138 0" fill="none" stroke="#17251d" stroke-opacity=".16" stroke-width="1.4"/><path d="M54 96v85m92-85v85" fill="none" stroke="#fff" stroke-opacity=".12" stroke-width="2"/></svg>`},
    mug:function(){return '<svg viewBox="0 0 180 210" aria-hidden="true"><defs><linearGradient id="mugbody" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#dce1da"/><stop offset=".22" stop-color="#fff"/><stop offset=".7" stop-color="#f7f8f3"/><stop offset="1" stop-color="#d9ded7"/></linearGradient><linearGradient id="mughandle"><stop stop-color="#d9ded7"/><stop offset=".5" stop-color="#fff"/><stop offset="1" stop-color="#d2d8d1"/></linearGradient></defs><ellipse cx="86" cy="181" rx="54" ry="9" fill="#233627" opacity=".12"/><path d="M126 79h12c25 0 25 48 0 48h-13" fill="none" stroke="#bfc8bf" stroke-width="18"/><path d="M126 79h12c25 0 25 48 0 48h-13" fill="none" stroke="url(#mughandle)" stroke-width="13"/><path d="M38 58h94v94q0 22-22 22H60q-22 0-22-22Z" fill="url(#mugbody)" stroke="#cbd2ca" stroke-width="1.5"/><ellipse cx="85" cy="59" rx="47" ry="9" fill="#fff" stroke="#d8ded7" stroke-width="1.5"/><ellipse cx="85" cy="60" rx="37" ry="5" fill="#d7ddd6" opacity=".52"/><path d="M46 72v77q0 13 11 17" fill="none" stroke="#fff" stroke-opacity=".75" stroke-width="3" stroke-linecap="round"/></svg>'},
    starter:function(){return '<svg viewBox="0 0 180 210" aria-hidden="true"><defs><linearGradient id="starterbox" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#fff"/><stop offset="1" stop-color="#e7ece2"/></linearGradient></defs><ellipse cx="96" cy="188" rx="58" ry="8" fill="#233627" opacity=".11"/><path d="M27 66h97l-5 113H35L27 66Z" fill="#cbd7c4"/><path d="M41 51h97l-5 113H49L41 51Z" fill="#e5dccd"/><path d="M57 35h97l-5 113H65L57 35Z" fill="url(#starterbox)" stroke="#cbd2c8" stroke-width="1.5"/><path d="m57 35 48 15 49-15M105 50v97" fill="none" stroke="#d9ded5" stroke-width="1.5"/><path d="M75 79h59m-59 8h42" stroke="#c6cec2" stroke-width="3" stroke-linecap="round"/></svg>'},
    starterplus:function(){return '<svg viewBox="0 0 180 210" aria-hidden="true"><defs><linearGradient id="starterplusbox" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#fff"/><stop offset="1" stop-color="#e9eee6"/></linearGradient></defs><ellipse cx="91" cy="189" rx="60" ry="8" fill="#233627" opacity=".11"/><path d="M20 70h98l-7 111H27L20 70Z" fill="#cbd7c4"/><path d="M47 48h100l-7 119H54L47 48Z" fill="url(#starterplusbox)" stroke="#cbd2c8" stroke-width="1.5"/><path d="m47 48 49 17 51-17M96 65v101" fill="none" stroke="#d9ded5" stroke-width="1.5"/><path d="M67 93h59m-59 8h39" stroke="#c6cec2" stroke-width="3" stroke-linecap="round"/><rect x="76" y="122" width="40" height="28" rx="8" fill="#e7e8df"/><path d="M96 128v16m-8-8h16" stroke="#9eaa98" stroke-width="2.5" stroke-linecap="round"/></svg>'},
    custom:function(c){const color=c||'#a4b995';return `<svg viewBox="0 0 180 210" aria-hidden="true"><ellipse cx="90" cy="184" rx="52" ry="8" fill="#233627" opacity=".1"/><path d="M57 56h66l-6 111H63L57 56Z" fill="${color}" stroke="#203025" stroke-opacity=".2" stroke-width="2"/><path d="M70 56q0-25 20-25t20 25" fill="none" stroke="#64735f" stroke-width="5"/><path d="M73 78h34m-34 9h22" stroke="#fff" stroke-opacity=".6" stroke-width="3" stroke-linecap="round"/><path d="M64 164q26 8 52 0" fill="none" stroke="#17251d" stroke-opacity=".22" stroke-width="2"/></svg>`}
  };
  const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch(_){return fallback}}
  let cart=read(CART_KEY,[]),filter='Alle',lastOrder=null;
  const grid=document.getElementById('productGrid');
  function renderProducts(){
    const shown=products.filter(p=>filter==='Alle'||p.category===filter);
    document.getElementById('shopCount').textContent=shown.length+' Artikel';
    grid.innerHTML=shown.map(p=>{
      const color=p.colors.length?'<div class="variant"><span class="variant-label">Farbe · <b data-color-name="'+p.id+'">'+esc(p.colors[0])+'</b></span><div class="swatches" role="group" aria-label="Farbe für '+esc(p.name)+'">'+p.colors.map((name,i)=>'<button type="button" class="swatch'+(i===0?' selected':'')+'" data-color-choice="'+p.id+'" data-value="'+i+'" style="--swatch:'+p.colorValues[i]+'" aria-label="'+esc(name)+'" aria-pressed="'+(i===0)+'" title="'+esc(name)+'"></button>').join('')+'</div></div>':'';
      const size=p.sizes.length?'<div class="variant"><span class="variant-label">Größe</span><div class="sizes" role="group" aria-label="Größe für '+esc(p.name)+'">'+p.sizes.map((s,i)=>'<button type="button" class="size-choice'+(i===0?' selected':'')+'" data-size-choice="'+p.id+'" aria-pressed="'+(i===0)+'">'+esc(s)+'</button>').join('')+'</div></div>':'';
      const action=p.available?'<button class="add" data-add="'+p.id+'" aria-label="'+esc(p.name)+' in den Warenkorb"><span aria-hidden="true">+</span></button>':'<span class="unavailable">Noch nicht bestellbar</span>';
      const price=p.price===null?'Preis folgt':money(p.price);
      return '<article class="card"><div class="visual"><span class="tag">'+esc(p.tag)+'</span><div class="art">'+art[p.kind](p.colors.length?p.colorValues[0]:'')+'</div>'+action+'</div><div class="info"><div><h3>'+esc(p.name)+'</h3><div class="meta">'+esc(p.description)+'</div></div><div class="price">'+price+'</div></div>'+(color||size?'<div class="options">'+color+size+'</div>':'')+'</article>';
    }).join('');
  }
  async function loadCustomProducts(){try{const response=await fetch('/api/catalog',{credentials:'same-origin'});if(!response.ok)return;const data=await response.json();for(const product of data.products||[]){if(products.some(p=>p.id===product.id))continue;products.push({...product,tag:'Neu im Shop',description:product.name+' · '+money(product.price),kind:'custom'})}renderProducts()}catch{}}
  function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));renderCart()}
  function renderCart(){
    const count=cart.reduce((n,x)=>n+Number(x.qty||0),0),total=cart.reduce((n,x)=>n+Number(x.price||0)*Number(x.qty||0),0);
    document.getElementById('cartCount').textContent=count;document.getElementById('cartTotal').textContent=money(total);document.getElementById('checkoutQuantity').textContent=count;document.getElementById('checkoutTotal').textContent=money(total);document.getElementById('checkoutButton').disabled=!count;
    document.getElementById('cartItems').innerHTML=count?cart.map((x,i)=>'<div class="line"><div class="thumb">'+art[x.kind](x.color||'')+'</div><div class="line-info"><h3>'+esc(x.name)+'</h3><small>'+esc([x.colorName,x.size].filter(Boolean).join(' · ')||'Ohne Variante')+'</small><div class="qty"><button data-qty="'+i+'" data-delta="-1" aria-label="Menge verringern">−</button><span>'+Number(x.qty)+'</span><button data-qty="'+i+'" data-delta="1" aria-label="Menge erhöhen">+</button><button class="remove" data-remove="'+i+'" aria-label="'+esc(x.name)+' entfernen" title="Entfernen"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m3 4v6m6-6v6"/></svg></button></div></div><div class="line-price">'+money(Number(x.price||0)*Number(x.qty||0))+'</div></div>').join(''):'<div class="empty"><b>Hier ist noch Platz.</b>Wähle deine Schoolstore-Lieblingsstücke.</div>';
  }
  function openCart(){document.getElementById('backdrop').classList.add('open');document.getElementById('cartDrawer').classList.add('open');document.getElementById('cartDrawer').setAttribute('aria-hidden','false')}
  function closeCart(){document.getElementById('backdrop').classList.remove('open');document.getElementById('cartDrawer').classList.remove('open');document.getElementById('cartDrawer').setAttribute('aria-hidden','true')}
  function toast(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
  grid.addEventListener('click',e=>{
    const btn=e.target.closest('[data-add]');if(!btn)return;
    const p=products.find(x=>x.id===btn.dataset.add),colorChoice=document.querySelector('[data-color-choice="'+p.id+'"].selected'),sizeChoice=document.querySelector('[data-size-choice="'+p.id+'"].selected');
    const colorIndex=colorChoice?Number(colorChoice.dataset.value):-1,colorName=colorIndex>=0?p.colors[colorIndex]:'',colorValue=colorIndex>=0?p.colorValues[colorIndex]:'',size=sizeChoice?sizeChoice.textContent:'';
    const key=[p.id,colorName,size].join('|'),existing=cart.find(x=>x.key===key);
    if(existing)existing.qty++;else cart.push({key,id:p.id,name:p.name,kind:p.kind,price:p.price,color:colorValue,colorName,size,qty:1});
    saveCart();toast(p.name+' im Warenkorb');
  });
  grid.addEventListener('click',e=>{
    const color=e.target.closest('[data-color-choice]'),size=e.target.closest('[data-size-choice]');
    if(color){const p=products.find(x=>x.id===color.dataset.colorChoice);color.parentElement.querySelectorAll('.swatch').forEach(x=>{const active=x===color;x.classList.toggle('selected',active);x.setAttribute('aria-pressed',String(active))});color.closest('.card').querySelector('[data-color-name]').textContent=p.colors[Number(color.dataset.value)];color.closest('.card').querySelector('.art').innerHTML=art[p.kind](p.colorValues[Number(color.dataset.value)])}
    if(size){size.parentElement.querySelectorAll('.size-choice').forEach(x=>{const active=x===size;x.classList.toggle('selected',active);x.setAttribute('aria-pressed',String(active))})}
  });
  document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');filter=btn.dataset.filter;renderProducts()}));
  document.getElementById('cartItems').addEventListener('click',e=>{const q=e.target.closest('[data-qty]'),r=e.target.closest('[data-remove]');if(q){const i=Number(q.dataset.qty);cart[i].qty+=Number(q.dataset.delta);if(cart[i].qty<1)cart.splice(i,1);saveCart()}if(r){cart.splice(Number(r.dataset.remove),1);saveCart()}});
  document.getElementById('openCart').addEventListener('click',openCart);document.getElementById('closeCart').addEventListener('click',closeCart);document.getElementById('backdrop').addEventListener('click',closeCart);
  document.getElementById('checkoutButton').addEventListener('click',()=>{if(!cart.length)return;closeCart();document.getElementById('checkoutModal').classList.add('open');document.getElementById('checkoutFormView').style.display='block';document.getElementById('receiptView').classList.remove('show')});
  document.getElementById('closeCheckout').addEventListener('click',()=>document.getElementById('checkoutModal').classList.remove('open'));
  document.getElementById('deliveryMethod').addEventListener('change',e=>{const child=e.target.value==='child';document.getElementById('childNameField').hidden=!child;document.getElementById('childClassField').hidden=!child;document.getElementById('otherPickupField').hidden=child;document.getElementById('childName').required=child;document.getElementById('childClass').required=child;document.getElementById('otherPickup').required=!child});
  document.getElementById('orderForm').addEventListener('submit',async e=>{
    e.preventDefault();if(!cart.length)return;
    const submit=e.currentTarget.querySelector('[type="submit"]'),label=submit.textContent;submit.disabled=true;submit.textContent='Wird übermittelt …';
    try{
      const f=new FormData(e.currentTarget),response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),email:f.get('email'),payment:f.get('payment'),delivery:f.get('delivery'),childName:f.get('childName'),childClass:f.get('childClass'),otherPickup:f.get('otherPickup'),note:f.get('note'),items:cart.map(x=>({id:x.id,colorName:x.colorName,size:x.size,qty:x.qty}))})});
      const data=await response.json();if(!response.ok)throw new Error(data.error||'Die Bestellung konnte nicht übermittelt werden.');
      lastOrder=data.order;document.getElementById('receiptName').textContent=String(lastOrder.customerName).split(' ')[0];
      const paymentInfo=lastOrder.payment==='transfer'?'<br><br><b>Überweisung innerhalb von 14 Tagen</b><br>Schoolstore eSG · IBAN DE41 3846 2135 1029 3090 15<br>Volksbank Oberberg eG':'<br><br><b>Barzahlung innerhalb von 7 Tagen</b><br>Bitte den Betrag im Lehrerzimmer bei Herrn Nievel oder Frau Köst abgeben.';
      document.getElementById('receiptDetails').innerHTML='<b>Bestellnummer:</b> '+esc(lastOrder.id)+'<br><b>Gesamtbetrag:</b> '+money(lastOrder.total)+'<br><b>Zahlungsart:</b> '+(lastOrder.payment==='transfer'?'Überweisung':'Barzahlung')+paymentInfo;
      document.getElementById('checkoutFormView').style.display='none';document.getElementById('receiptView').classList.add('show');cart=[];saveCart();e.currentTarget.reset();document.getElementById('deliveryMethod').dispatchEvent(new Event('change'));
    }catch(error){toast(error.message)}finally{submit.disabled=false;submit.textContent=label;}
  });
  document.getElementById('printReceipt').addEventListener('click',()=>window.printSchoolstoreInvoice(lastOrder));
  document.getElementById('receiptDone').addEventListener('click',()=>document.getElementById('checkoutModal').classList.remove('open'));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();document.getElementById('checkoutModal').classList.remove('open')}});
  renderProducts();loadCustomProducts();renderCart();document.getElementById('deliveryMethod').dispatchEvent(new Event('change'));
})();

